(function(){var a="area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed,source,path,animateanimateColor,circle,ellipse,glyph,hatchpath,image,line,mpath,path,polygon,polyline,rect,solidcolorstop,tref,use,view,",a=a.split(","),b="colgroup dd dt li options p td tfoot th thead tr".split(" "),c={current:null,queue:{local:[],global:[]},enqueue:function(a){this.queue.local=this.queue.local.concat(a);setTimeout(function(){c.processQueue()},0)},processQueue:function(){if(!this.current){for(;this.queue.local.length;)this.queue.global.unshift(this.queue.local.pop());
if(this.queue.global.length){var a=this.queue.global.shift(),b=document.getElementById(a.id);switch(a.type){case "external":var d=document.createElement("script");this.current=d;var e=function(){d.onload=d.onerror=d.onreadystatechange=null;c.current=null;c.processQueue()};"onload"in d?(d.onload=e,d.onerror=e):d.onreadystatechange=function(){"loaded"==d.readyState&&e()};d.src=a.src;b.parentNode.replaceChild(d,b);break;case "inline":c.current=b,(0,eval)(a.code),c.current=null,b.parentNode&&b.parentNode.removeChild(b),
c.processQueue()}}}}},d=0,e=function(a,c){var b=document.createDocumentFragment(),d=document.createElement("div");for(d.innerHTML=c;d.firstChild;)b.appendChild(d.firstChild);"script"==a.nodeName.toLowerCase()||0==a.id.indexOf("dw-tmp-")?a.parentNode.insertBefore(b,a):a.appendChild(b)},g=function(a,b){var f=[],g=/src=['"]?([^\s'"]+)/i,l=/src=['"]?([^\s'"]+['"]?)/i,h=b.replace(/<script(.*?)>([\s\S]*?)<\/script>/ig,function(a,b,c){a="dw-tmp-"+d++;var e=b.match(g);e?f.push({type:"external",id:a,src:e[1]}):
f.push({type:"inline",id:a,code:c});b=("<script"+b+">\x3c/script>").replace(l,"");return"<span id='"+a+"'></span>"+b});e(a,h);c.enqueue(f)},f={code:"",node:null,append:function(a,b){this.node!=a&&(this.code="",this.node=a);this.code+=b;this.isWritable()&&(b=this.code,this.code="",g(this.node,b))},isWritable:function(){for(var c=this.code.replace(/<script[\s\S]*?<\/script>/gi,""),d=c.match(/<[a-z0-9-]+[\s>]/ig)||[],e=c.match(/<\/[a-z0-9-]+/ig)||[],f=[],g=[],h=c=0;h<d.length;h++){var k=d[h].substring(1).toLowerCase(),
k=k.substring(0,k.length-1);-1<a.indexOf(k)||-1<b.indexOf(k)||(c++,f.push(k))}for(h=d=0;h<e.length;h++)k=e[h].substring(2).toLowerCase(),-1<b.indexOf(k)||(d++,g.push(k));"DCWRT_DEBUG"in window&&"function"===typeof window.CustomEvent&&"function"===typeof window.dispatchEvent&&(e={status:!0,tagsOpen:f,tagsClose:g,countOpen:c,countClose:d},c!=d&&(e.status=!1),e=new CustomEvent("documentWriteIsWritable",{detail:e}),window.dispatchEvent(e));return c!=d?!1:!0}},l=function(){for(var a=document.getElementsByTagName("script"),
a=c.current||a[a.length-1]||document.body,b="",d=0;d<arguments.length;d++)b+=arguments[d];f.append(a,b)};window.replaceDocumentWrite=function(){document.write=l;document.writeln=l;document.writeTo=g}})();if(!window.im){var im={returnedAds:[]};document.addEventListener&&document.addEventListener("DOMContentLoaded",function(){var a=document.createElement("script");a.src="//i.imedia.cz/js/sync_codes.js";document.body.insertBefore(a,document.body.firstChild)});im.conf={urlLength:2E3,params:"zoneId section collocation source passon flag spotId".split(" "),protocol:location.protocol.match(/s/i)?"https":"http",server:"i.imedia.cz",charset:"utf-8",referer:window.location.href?window.location.href:""};im._browserHash=
{computeHash:function(){var a=[],b;for(b in screen)a.push(screen[b]);var c=this.getPlugins();for(b=0;b<c.length;b++)a.push(c[b]);var a=a.join("").toLowerCase(),c=[0,0,0,0],d=0;for(b=0;b<a.length;b++)c[d]=(c[d]+a.charCodeAt(b))%65535,d=(d+1)%c.length;return c.join("")},getPlugins:function(){var a=[];if(navigator.plugins&&navigator.plugins.length)for(var b=0;b<navigator.plugins.length;b++){var c=navigator.plugins[b],c=c.name.match(/[0-9]/)?c.name:c.description;a.push(c)}else if(window.ActiveXObject){var b=
{"AcroPDF.PDF":function(){return this.GetVersions()},"PDF.PdfCtrl":function(){return this.GetVersions()},"ShockwaveFlash.ShockwaveFlash":function(){return this.GetVariable("$version")},"QuickTime.QuickTime":function(){return this.QuickTimeVersion},"rmocx.RealPlayer G2 Control":function(){return this.GetVersionInfo()},"rmocx.RealPlayer G2 Control.1":function(){return this.GetVersionInfo()},"RealPlayer.RealPlayer(tm) ActiveX Control (32-bit)":function(){return this.GetVersionInfo()},"RealVideo.Rep.CalVideo(tm) ActiveX Control (32-bit)":function(){return this.GetVersionInfo()},
RealPlayer:function(){return this.GetVersionInfo()},"WMPlayer.OCX":function(){return this.versionInfo}},d,e;for(e in b){try{d=new ActiveXObject(e),c=e}catch(g){continue}try{c+=" "+b[e].call(d)}catch(f){}a.push(c)}}return a}};im._onReadyStateChange=function(a,b,c){a=a.target;4==a.readyState&&200==a.status&&(a.onreadystatechange=null,this._done(a.responseText,b,c))};im._onXDomainRequestLoad=function(a,b,c){this._done(a.responseText,b,c)};im._done=function(a,b,c){try{var d=JSON.parse(a)}catch(e){return}a=
d.ads;(d=d.opt)&&im._parseOpt(d);if(c&&c.AMPcallback)c.AMPcallback(a);else for(im.returnedAds.push(im._setMapping(b,a)),c=0;c<a.length;c++){var g=a[c],d=b[c];d.callback?d.callback(g,d):this.writeAd(g,d)}};im._setMapping=function(a,b){for(var c=[],d=0;d<a.length;d++){var e=a[d],g=b[d].spots;if(g){e.spots=[];for(var f=0;f<g.length;f++)e.spots.push(g[f].spotId)}c.push(e)}return c};im.getAds=function(a,b){if(a.length){window.replaceDocumentWrite();this._logAds(a);for(var c=this._buildPrefix(),d=this.conf.protocol+
"://"+this.conf.server+"/json",e=0;e<a.length;e++)var g=this._buildItem(a[e],e,b),c=c+("&"+g);if(window.XMLHttpRequest){var f=new XMLHttpRequest;this._xdomain=!1;window.XDomainRequest&&!f.upload&&(this._xdomain=!0,f=new XDomainRequest,f.onprogress=function(){},f.ontimeout=function(){},f.onerror=function(){})}else throw Error("No XHR available");(function(a,b,e){e._xdomain?f.onload=function(c){e._onXDomainRequestLoad(f,a,b)}:f.onreadystatechange=function(c){e._onReadyStateChange(c,a,b)};f.open("POST",
d);f.withCredentials=!0;e._xdomain||f.setRequestHeader("Content-type","application/x-www-form-urlencoded");f.send(c)})(a,b,this)}};im.writeAd=function(a,b,c){if(c="string"==typeof b.id?document.getElementById(b.id):b.id){for(var d=0;d<a.spots.length;d++)im._writeSpot(a.spots[d],c,b);a.impress&&(c.className+=" adFull");a.miss&&document.writeTo(c,a.miss);b.scroll&&im._scroll(c)}};im._writeSpot=function(a,b,c){var d="iframe"==b.nodeName.toLowerCase();if(a.iframe){var e=document.createElement("iframe");
e.id="im-"+Math.random().toString(16).replace(".","");e.frameBorder="0";d?(e.width=b.width,e.height=b.height,b.parentNode.replaceChild(e,b)):(e.width="100%",e.height="100%","width"in a&&(e.width=a.width+2),"height"in a&&(e.height=a.height+2),b.appendChild(e));var g="<script>window.__im_passback_iframe_id = '"+e.id+"'\x3c/script>"+a.content;e.onload=function(){e.onload=null;e.contentWindow.postMessage(g,"*")};e.src=im.conf.protocol+"://"+im.conf.server+"/html/"+window.location.host+"/reklama.html?url="+
encodeURIComponent(window.location.href);this._iframes.push({iframe:e,position:c})}else d&&(d=document.createElement("div"),b.parentNode.replaceChild(d,b),b=d),c.secure?b.innerHTML+=a.content:document.writeTo(b,a.content)};im.clearContext=function(){this.zoneToId={};this._iframes=[]};im.clearContext();im._scroll=function(a){for(var b=a.offsetHeight,c=0;a;)c+=a.offsetTop,a=a.offsetParent;a=document.documentElement.scrollTop||document.body.scrollTop;var d=document.documentElement.scrollLeft||document.body.scrollLeft;
a>c+b&&scrollTo(d,a+b)};im.videoAds=function(a,b,c,d){function e(b,c){g--;var d=c.zoneId.split(".").pop().replace(/-/g,""),e=b.spots,h="";""!=b.miss&&(h+=b.miss);for(var k=0;k<e.length;k++)h+=e[k].content;e=document.getElementById(a);(h=im._parseVideoAd(h,e))&&(f[d]=h);!g&&(d=document.getElementById(a))&&(h=d.getElementsByTagName("embed"),h.length&&(d=h[0]),d.setAds(f))}b=b.split(",");for(var g=b.length,f={},l=[],m=0;m<b.length;m++)l.push({callback:e,zoneId:b[m],section:c,collocation:d});this.getAds(l,
!0);return!0};im._buildPrefix=function(){var a={charset:this.conf.charset,cookieEnabled:navigator.cookieEnabled?1:0,lang:(navigator.language||navigator.systemLanguage||"").substring(0,2),bhash:im._browserHash.computeHash()};""!=this.conf.referer&&(a.referer=this.conf.referer);var b=[],c;for(c in a)b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return"mode=json2&"+b.join("&")};im._buildItem=function(a,b,c){this.zoneToId[a.zoneId]=a.id;a.passons&&(a.passon=a.passons);if(!(c&&c.AMPcallback||
a.callback||("string"==typeof a.id?document.getElementById(a.id):a.id)))throw Error("No callback and invalid ID passed to IM ("+a.id+")");c=[];for(var d=0;d<this.conf.params.length;d++){var e=this.conf.params[d];if(e in a){var g=a[e],e=encodeURIComponent(e)+"-"+b;if("object"==typeof g)for(var f in g)c.push(e+"."+encodeURIComponent(f)+"="+encodeURIComponent(g[f]));else c.push(e+"="+encodeURIComponent(g))}}return c.join("&")};im._logAds=function(a){if(window.DOT){for(var b={},c=0;c<a.length;c++)b[a[c].zoneId]=
!0;a=[];for(var d in b)d in{}||a.push(d);DOT.hit("ad",{d:{zones:a.join(",")}})}};im._parseVideoAd=function(a,b){var c,d=[];c=a.replace(/\x3c!--(.*?)--\x3e/g,function(a,b){d.push(b);return""});for(var e=0;e<d.length;e++){var g=document.createComment(d[e]);0==e?b.parentNode.insertBefore(g,b):b.parentNode.insertBefore(g,b.nextSibling)}c=c.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'");if(e=c.match(/^\s*<img *src *= *(['"])(.*?)\1[^>]*\/>\s*$/i))return[{miss:e[2]}];
c=c.replace(/<img.*?\/>/g,"");c=c.replace(/}\s*{/g,"},{");return c.match(/^[\s]*$/)?null:eval("["+c+"]")};im._receiveMessage=function(a){var b=a.data;if("string"==typeof edata)try{b=JSON.parse(b)}catch(c){return}if("fallback"==b.msg||"passback"==b.msg){for(var d=null,e=0;e<im._iframes.length;e++)if(im._iframes[e].iframe.contentWindow==a.source){d=im._iframes[e];break}d&&(a=b.ad,"string"==typeof a&&(a={content:a,iframe:!0}),im._writeSpot(a,d.iframe,d.position))}};window.addEventListener?window.addEventListener("message",
im._receiveMessage,!1):window.attachEvent&&window.attachEvent("onmessage",im._receiveMessage);im._parseOpt=function(a){a.pub_sync&&im._pubmaticSync();a.apn_sync&&im._appnexusSync()};im._createIframeSync=function(){var a=document.createElement("iframe");a.width=0;a.height=0;a.style.display="none";return a};im._pubmaticSync=function(){var a=im._createIframeSync();a.src="//ads.pubmatic.com/AdServer/js/user_sync.html?p=49307&predirect="+encodeURIComponent("//"+im.conf.server+"/html/pub_sync.html?pmId=");
document.body.insertBefore(a,document.body.firstChild)};im._appnexusSync=function(){var a=im._createIframeSync();a.src="//secure.adnxs.com/getuid?//"+im.conf.server+"/html/apn_sync.html?uid=$UID";document.body.insertBefore(a,document.body.firstChild)}};
//# sourceMappingURL=im3.js.map
